site_name: SeedSync
site_description: Sync files from a remote Linux server to a local machine with LFTP and a web UI
theme:
  name: material
  language: en
  palette:
    scheme: preference
    primary: teal
    accent: teal
    font: false
  logo: images/logo.png
  favicon: images/favicon.png
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
repo_name: truedarkdev/seedsync
repo_url: https://github.com/truedarkdev/seedsync
nav:
  - Home: index.md
  - Installation: install.md
  - Usage: usage.md
  - FAQ: faq.md
