from typing import TypeAlias
from pexpect import exceptions

_Pattern: TypeAlias = str | type[exceptions.EOF] | type[exceptions.TIMEOUT]

class PopenSpawn:
    before: bytes | str | None
    after: bytes | str | type[exceptions.EOF] | type[exceptions.TIMEOUT] | None
    exitstatus: int | None
    def __init__(self, cmd: str | list[str], timeout: int = 30, maxread: int = 2000,
                 searchwindowsize: int | None = None, logfile: object | None = None,
                 cwd: str | None = None, env: dict[str, str] | None = None,
                 encoding: str | None = None, codec_errors: str = "strict") -> None: ...
    def expect(self, pattern: _Pattern | list[_Pattern], timeout: float = -1,
               searchwindowsize: int = -1) -> int: ...
    def send(self, s: str = "") -> int: ...
    def sendline(self, s: str = "") -> int: ...
    def isalive(self) -> bool: ...
    def close(self, force: bool = True) -> None: ...
    def wait(self) -> int: ...
